const catalog={
  "京都":{area:"京都",category:"歴史と町歩き",spots:[{name:"清水寺",kind:"寺院 · 京都を代表する景色",emoji:"⛩",duration:"90分",tag:"culture"},{name:"二年坂・三年坂",kind:"石畳の町並み · 甘味処めぐり",emoji:"🏮",duration:"60分",tag:"culture"},{name:"錦市場",kind:"京の台所 · 食べ歩き",emoji:"🍡",duration:"75分",tag:"food"},{name:"祇園・花見小路",kind:"町家の風情 · 夕暮れさんぽ",emoji:"🏮",duration:"60分",tag:"culture"},{name:"南禅寺・水路閣",kind:"静かな境内 · レンガのアーチ",emoji:"🌿",duration:"75分",tag:"nature"},{name:"京都国立博物館",kind:"日本美術 · 企画展示",emoji:"🖼️",duration:"90分",tag:"art"},{name:"嵐山・竹林の小径",kind:"竹林さんぽ · 渡月橋エリア",emoji:"🎋",duration:"90分",tag:"nature"},{name:"伏見稲荷大社",kind:"千本鳥居 · お山めぐり",emoji:"⛩",duration:"90分",tag:"culture"},{name:"先斗町で京ごはん",kind:"鴨川沿い · 夜の小路",emoji:"🍵",duration:"90分",tag:"food"},{name:"京都駅ビル・伊勢丹",kind:"おみやげ探し · 展望スポット",emoji:"🛍️",duration:"60分",tag:"shopping"}]},
  "東京":{area:"東京",category:"街とカルチャー",spots:[{name:"浅草寺・仲見世",kind:"下町さんぽ · 老舗の味",emoji:"🏮",duration:"90分",tag:"culture"},{name:"上野公園・博物館",kind:"ミュージアム · 緑の散策",emoji:"🖼️",duration:"90分",tag:"art"},{name:"築地場外市場",kind:"朝の食べ歩き · 江戸前グルメ",emoji:"🍣",duration:"75分",tag:"food"},{name:"谷中銀座",kind:"レトロな商店街 · 猫のいる町",emoji:"🐈",duration:"60分",tag:"culture"},{name:"明治神宮",kind:"森の参道 · 都心の静けさ",emoji:"🌳",duration:"75分",tag:"nature"},{name:"表参道・青山",kind:"建築とショップめぐり",emoji:"🛍️",duration:"90分",tag:"shopping"},{name:"チームラボプラネッツ",kind:"没入型アート体験",emoji:"✨",duration:"90分",tag:"art"},{name:"東京スカイツリー",kind:"街を一望 · ソラマチ散策",emoji:"🌇",duration:"90分",tag:"nature"},{name:"神楽坂",kind:"路地裏さんぽ · 和洋の食文化",emoji:"🍷",duration:"90分",tag:"food"},{name:"渋谷・スクランブル交差点",kind:"東京らしい街の風景",emoji:"🌆",duration:"45分",tag:"shopping"}]},
  "大阪":{area:"大阪",category:"食いだおれと街遊び",spots:[{name:"大阪城公園",kind:"城郭と庭園 · 歴史さんぽ",emoji:"🏯",duration:"90分",tag:"culture"},{name:"黒門市場",kind:"大阪の台所 · 海鮮食べ歩き",emoji:"🐙",duration:"75分",tag:"food"},{name:"道頓堀・戎橋",kind:"ネオンと大阪グルメ",emoji:"🍜",duration:"75分",tag:"food"},{name:"中之島美術館",kind:"現代美術 · 水辺の建築",emoji:"🖼️",duration:"90分",tag:"art"},{name:"新世界・通天閣",kind:"レトロな街並み · 串カツ",emoji:"🏮",duration:"90分",tag:"culture"},{name:"心斎橋筋商店街",kind:"老舗から最新までお買い物",emoji:"🛍️",duration:"90分",tag:"shopping"},{name:"天王寺公園・てんしば",kind:"芝生広場 · 展望台",emoji:"🌿",duration:"75分",tag:"nature"},{name:"法善寺横丁",kind:"石畳の路地 · 夕食スポット",emoji:"🍶",duration:"75分",tag:"food"},{name:"梅田スカイビル",kind:"空中庭園からの夕景",emoji:"🌇",duration:"75分",tag:"nature"},{name:"国立国際美術館",kind:"地下に広がる現代アート",emoji:"🎨",duration:"90分",tag:"art"}]},
  "台北":{area:"台北",category:"街角とローカルグルメ",spots:[{name:"龍山寺",kind:"色鮮やかな寺院 · 萬華散策",emoji:"🏮",duration:"75分",tag:"culture"},{name:"迪化街",kind:"問屋街さんぽ · お茶と乾物",emoji:"🫖",duration:"90分",tag:"culture"},{name:"永康街",kind:"小籠包とカフェめぐり",emoji:"🥟",duration:"90分",tag:"food"},{name:"中正紀念堂",kind:"広場と建築 · 歴史スポット",emoji:"🏛️",duration:"75分",tag:"culture"},{name:"台北101・信義エリア",kind:"展望台 · お買い物",emoji:"🌆",duration:"90分",tag:"shopping"},{name:"華山1914文化創意産業園区",kind:"リノベ空間 · 展示とカフェ",emoji:"🎨",duration:"90分",tag:"art"},{name:"象山ハイキング",kind:"街を望む展望スポット",emoji:"⛰️",duration:"90分",tag:"nature"},{name:"饒河街夜市",kind:"屋台グルメ · 夜の街歩き",emoji:"🍢",duration:"90分",tag:"food"},{name:"故宮博物院",kind:"中国美術の名品を鑑賞",emoji:"🖼️",duration:"120分",tag:"art"},{name:"大稲埕の夕景",kind:"淡水河沿い · 夕暮れさんぽ",emoji:"🌇",duration:"60分",tag:"nature"}]},
  "パリ":{area:"パリ",category:"美術と街角の風景",spots:[{name:"ルーヴル美術館",kind:"名作をめぐる · 予約推奨",emoji:"🖼️",duration:"120分",tag:"art"},{name:"チュイルリー庭園",kind:"美術館のあとにひと休み",emoji:"🌿",duration:"60分",tag:"nature"},{name:"マレ地区",kind:"パリらしい路地 · ブティック",emoji:"🛍️",duration:"90分",tag:"shopping"},{name:"サンジェルマン・デ・プレ",kind:"カフェと書店 · 左岸さんぽ",emoji:"☕",duration:"90分",tag:"culture"},{name:"オルセー美術館",kind:"印象派コレクション · 予約推奨",emoji:"🎨",duration:"120分",tag:"art"},{name:"サン・マルタン運河",kind:"水辺の散歩 · ローカルな景色",emoji:"🚲",duration:"75分",tag:"nature"},{name:"モンマルトル",kind:"丘の上の街 · サクレ・クール寺院",emoji:"⛪",duration:"90分",tag:"culture"},{name:"パッサージュめぐり",kind:"屋根付き商店街 · 雨の日にも",emoji:"🏛️",duration:"75分",tag:"shopping"},{name:"マルシェでランチ",kind:"チーズやパン · 地元の味",emoji:"🥐",duration:"75分",tag:"food"},{name:"セーヌ川沿いの夕景",kind:"川辺の散歩 · 橋めぐり",emoji:"🌇",duration:"60分",tag:"nature"}]}
};
const genericSpots=[{name:"街のシンボル・中心エリア",kind:"まずは街の雰囲気をつかむ散策",emoji:"⌖",duration:"75分",tag:"culture"},{name:"ローカルマーケット",kind:"地元の食材や名物をのぞく",emoji:"🍴",duration:"75分",tag:"food"},{name:"歴史地区を歩く",kind:"建築や町並みから土地の物語に触れる",emoji:"🏛️",duration:"90分",tag:"culture"},{name:"街のミュージアム",kind:"地域の文化やアートを楽しむ",emoji:"🖼️",duration:"90分",tag:"art"},{name:"公園・展望スポット",kind:"景色を眺めてひと休み",emoji:"🌿",duration:"75分",tag:"nature"},{name:"地元の商店街",kind:"気になるお店でおみやげ探し",emoji:"🛍️",duration:"75分",tag:"shopping"},{name:"人気のカフェエリア",kind:"街角のカフェでゆっくり",emoji:"☕",duration:"60分",tag:"food"},{name:"夕暮れの散歩道",kind:"景色のいい場所で一日の締めくくり",emoji:"🌇",duration:"60分",tag:"nature"},{name:"名物料理のお店",kind:"この街ならではの味を楽しむ",emoji:"🍽️",duration:"90分",tag:"food"},{name:"アート・カルチャー施設",kind:"展示やイベントをチェック",emoji:"🎨",duration:"90分",tag:"art"}];
const fallbackNames={"京都":/kyoto/i,"東京":/tokyo/i,"大阪":/osaka/i,"台北":/taipei/i,"パリ":/paris/i};
const $=s=>document.querySelector(s);const DRAFT_KEY="tabi-current-draft",SAVED_KEY="tabi-saved-trips";let trip=null,activeDay=0,toastTimer,savedTrips=[],draftTimer,draftQueue=Promise.resolve(),travelMode="TRANSIT",routeRequestId=0;const officialSiteRequests=new Map();let deletedTrips=[],savedView="active",routesUpdatingAll=false,routesUpdatingTrip=null,routesUpdatingMode=null,routeUpdatePromise=Promise.resolve();const deletingTripIds=new Set();
const pad=n=>String(n).padStart(2,"0");const localISO=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;const parseLocal=s=>new Date(`${s}T12:00:00`);const dateLabel=(d,opts={month:"short",day:"numeric"})=>new Intl.DateTimeFormat("ja-JP",opts).format(d);const dateRange=(a,b)=>{const x=parseLocal(a),y=parseLocal(b);return `${x.getFullYear()}年${x.getMonth()+1}月${x.getDate()}日 〜 ${y.getMonth()+1}月${y.getDate()}日`};const dayCount=(a,b)=>Math.round((parseLocal(b)-parseLocal(a))/86400000)+1;
function serializeTrip(source=trip){return JSON.parse(JSON.stringify({...source,days:source.days.map(day=>({...day,date:day.date instanceof Date?day.date.toISOString():day.date}))}))}
function enqueueDraftSave(snapshot){draftQueue=draftQueue.catch(()=>{}).then(async()=>{const response=await fetch("/api/storage/draft",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({draft:snapshot})});if(!response.ok)throw new Error("DBへの保存に失敗しました");if(!deletingTripIds.has(snapshot.id)&&savedTrips.some(item=>item.id===snapshot.id)){const saved=await fetch("/api/storage/saved",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({trip:snapshot})});if(!saved.ok)throw new Error("DBへの保存に失敗しました");updateStorageLists(await saved.json())}}).catch(error=>toast(error.message))}
function persistDraft(){if(!trip)return;const snapshot=serializeTrip({...trip,activeDay});clearTimeout(draftTimer);draftTimer=setTimeout(()=>enqueueDraftSave(snapshot),250)}
function flushDraft(){if(!trip)return Promise.resolve();clearTimeout(draftTimer);enqueueDraftSave(serializeTrip({...trip,activeDay}));return draftQueue}
function restoreDraft(draft){if(!draft?.days?.length)return false;try{const legacy=savedTrips.find(item=>item.destination===draft.destination&&item.startDate===draft.startDate);trip={...draft,initialTravelMode:draft.initialTravelMode||draft.travelMode||"TRANSIT",id:draft.id||legacy?.id||TabiSchedule.createId(),travelMode:draft.travelMode||travelMode,days:draft.days.map(day=>({...day,date:new Date(day.date)}))};travelMode=trip.travelMode;$("#route-mode").value=travelMode;activeDay=Math.min(draft.activeDay||0,trip.days.length-1);$("#departure-point").value=trip.departurePoint||"";$("#destination").value=trip.destination;$("#start-date").value=trip.startDate;$("#end-date").value=trip.endDate;$("#end-date").min=trip.startDate;$("#pace").value=trip.pace;document.querySelectorAll(".chip input").forEach(input=>{input.checked=trip.interests.includes(input.value);input.closest(".chip").classList.toggle("selected",input.checked)});render();return true}catch(error){console.error("Could not restore the itinerary:",error);return false}}
async function initializeStorage(){try{const response=await fetch("/api/storage",{cache:"no-store"});if(!response.ok)throw new Error();const stored=await response.json();savedTrips=stored.saved||[];deletedTrips=stored.deleted||[];let draft=stored.draft;try{const oldDraft=JSON.parse(localStorage.getItem(DRAFT_KEY)||"null"),oldSaved=JSON.parse(localStorage.getItem(SAVED_KEY)||"[]");if(!draft&&oldDraft?.days?.length){draft=oldDraft;const migrated=await fetch("/api/storage/draft",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({draft})});if(!migrated.ok)throw new Error()}for(const oldTrip of oldSaved){const migrated=await fetch("/api/storage/saved",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({trip:oldTrip})});if(!migrated.ok)throw new Error();savedTrips=(await migrated.json()).saved}localStorage.removeItem(DRAFT_KEY);localStorage.removeItem(SAVED_KEY)}catch(error){console.warn("Previous browser-saved trips could not be migrated:",error.message)}updateSaved();if(draft?.days?.length){if(!restoreDraft(draft))renderStorageError("保存した旅程を表示できませんでした。")}else renderEmpty()}catch{renderStorageError("保存データベースに接続できません。VPN接続を確認してください。")}}
function renderStorageError(message){renderEmpty();const note=document.createElement("p"),retry=document.createElement("button");note.className="empty-day";note.textContent=message;retry.type="button";retry.className="add-event-button";retry.textContent="旅程を再読み込み";retry.addEventListener("click",async()=>{retry.disabled=true;await initializeStorage()});$("#day-content").replaceChildren(note,retry);toast(message)}
function renderEmpty(){trip=null;$("#result-destination").textContent="旅程";$("#result-suffix").textContent="";$("#trip-summary").textContent="行き先と日程を決め、「旅程をつくる」を押してください。";$("#overview-dates").textContent="—";$("#overview-days").textContent="—";$("#overview-pace").textContent="—";$("#day-tabs").innerHTML="";$("#day-content").innerHTML='<p class="empty-day">旅程を作成すると、日ごとの予定がここに表示されます。</p>';$("#share-button").disabled=true;$("#save-button").disabled=true;$("#regenerate-button").disabled=true}
async function checkApiStatus(){const status=$("#api-status");try{const response=await fetch("/api/status");const data=await response.json();status.innerHTML=data.configured?'<span>✓</span> GPT-6 Luna API · 条件をOpenAIへ送信':'<span>!</span> .env にAPIキーを設定してください'}catch{status.innerHTML='<span>!</span> APIサーバーに接続できません'}}
function initializeDates(){const start=new Date();start.setDate(start.getDate()+14);const end=new Date(start);end.setDate(end.getDate()+2);$("#start-date").value=localISO(start);$("#end-date").value=localISO(end);$("#start-date").min=localISO(new Date());$("#start-date").addEventListener("change",()=>{$("#end-date").min=$("#start-date").value;if($("#end-date").value<$("#start-date").value)$("#end-date").value=$("#start-date").value});$("#end-date").min=$("#start-date").value}
function getCatalog(destination){const cleaned=destination.trim();if(catalog[cleaned])return catalog[cleaned];for(const [name,re] of Object.entries(fallbackNames))if(re.test(cleaned))return catalog[name];return {area:cleaned,category:"街歩きとローカル体験",spots:genericSpots}}
function buildTrip({destination,startDate,endDate,pace,interests}){const count=dayCount(startDate,endDate);if(count<1||count>21)throw Error("旅行日数は1〜21日の範囲で設定してください。");const base=getCatalog(destination);let pool=base.spots.filter(s=>interests.length===0||interests.includes(s.tag));if(pool.length<4){for(const spot of base.spots)if(!pool.includes(spot)){pool.push(spot);if(pool.length>=4)break}}const perDay=pace==="relaxed"?3:pace==="active"?5:4;const days=[];for(let d=0;d<count;d++){const events=[];for(let i=0;i<perDay;i++){const spot=pool[(d*perDay+i)%pool.length];events.push({...spot,time:(pace==="relaxed"?["09:30","13:00","16:00"]:pace==="active"?["08:30","10:45","13:15","15:30","18:00"]:["09:00","11:30","14:00","17:00"])[i],id:`${d}-${i}-${Math.random().toString(36).slice(2,7)}`})}days.push({date:new Date(parseLocal(startDate).getTime()+d*86400000),events})}return {id:TabiSchedule.createId(),destination:destination.trim(),startDate,endDate,pace,interests,days,category:base.category}}
function render(){if(!trip)return;activeDay=Math.min(activeDay,trip.days.length-1);$("#result-destination").textContent=trip.destination;$("#result-suffix").textContent="の旅程";$("#overview-dates").textContent=dateRange(trip.startDate,trip.endDate);$("#overview-days").textContent=`${trip.days.length}日間`;$("#overview-pace").textContent={relaxed:"ゆったり",balanced:"ちょうどいい",active:"たっぷり満喫"}[trip.pace];$("#trip-summary").textContent=`${trip.departurePoint?`${trip.departurePoint}から${trip.destination}へ。`:""}${trip.destination}で過ごす${trip.days.length}日間。${trip.category}を楽しむ旅のプランです。`;$("#share-button").disabled=Boolean(trip.routeModePending)||routesUpdatingAll;$("#save-button").disabled=routesUpdatingAll;$("#regenerate-button").disabled=false;renderTabs();renderDay();updateSaved();persistDraft()}
function renderTabs(){$("#day-tabs").innerHTML=trip.days.map((d,i)=>`<button class="day-tab ${i===activeDay?"active":""}" type="button" role="tab" aria-selected="${i===activeDay}" data-day="${i}"><small>DAY ${String(i+1).padStart(2,"0")} · ${dateLabel(d.date,{weekday:"long"})}</small><strong>${dateLabel(d.date,{month:"numeric",day:"numeric"})}</strong></button>`).join("");$("#day-tabs").querySelectorAll(".day-tab").forEach(b=>b.addEventListener("click",()=>{activeDay=Number(b.dataset.day);renderTabs();renderDay()}))}
function foodTarget(day){const meals=TabiSchedule.mealEvents(day);return meals.find(event=>event.id===(day.foodTargetId??meals[0]?.id))||null}
function renderFoodRecommendations(day){
 const items=day.foodRecommendations||[];if(!items.length)return "";
 const meals=TabiSchedule.mealEvents(day),target=foodTarget(day),newTime=day.foodNewTime||"12:00",busy=day.events.some(event=>event.editing)||routesUpdatingAll&&routesUpdatingTrip===trip;
 return `<section class="food-picks" aria-labelledby="food-picks-title"><div class="food-picks-heading"><div><h4 id="food-picks-title">この日の周辺グルメ</h4><p>観光の近くで楽しめる、名物・名店の候補。</p></div><span class="food-picks-count">${items.length}候補</span></div><div class="food-target-bar"><label for="food-target">入れる予定<select id="food-target" ${busy?"disabled":""}>${meals.map(event=>`<option value="${escapeHTML(event.id)}" ${target===event?"selected":""}>${escapeHTML(event.time)} · ${escapeHTML(event.name)}</option>`).join("")}<option value="" ${!target?"selected":""}>新しい食事予定を追加</option></select></label>${!target?`<label class="food-new-time">開始時刻<input id="food-new-time" type="time" value="${escapeHTML(newTime)}" ${busy?"disabled":""}></label>`:""}<p>${target?"選んだ食事予定を、おすすめのお店に変更します。":"1時間の食事予定を追加し、移動時間を再計算します。"}</p></div><div class="food-picks-list">${items.map((item,index)=>{
 const added=Boolean(TabiSchedule.foodPickEvent(day,item)),url=safeOfficialURL(item.url);
 return `<article class="food-pick ${added?"is-added":""}"><span class="food-pick-number">${String(index+1).padStart(2,"0")}</span><div class="food-pick-copy"><h5>${escapeHTML(item.name)}</h5><p class="food-specialty">${escapeHTML(item.specialty)}</p><p class="food-nearby">⌖ ${escapeHTML(item.nearbyTo)}周辺</p><p class="food-reason">${escapeHTML(item.reason)}</p>${url?`<a class="food-source" href="${escapeHTML(url)}" target="_blank" rel="noopener noreferrer">お店の情報・出典 ↗</a>`:""}</div><button type="button" class="food-pick-button" data-food-pick="${index}" ${added||busy?"disabled":""}>${added?"✓ 予定に入っています":target?`${escapeHTML(target.time)}の食事に入れる`:`${escapeHTML(newTime)}に追加`}</button></article>`
 }).join("")}</div></section>`;
}
function renderDayBase(){
 const day=trip.days[activeDay],date=dateLabel(day.date,{year:"numeric",month:"long",day:"numeric",weekday:"long"});
 $("#day-content").innerHTML=`<div class="day-title-row"><div><h3>DAY ${String(activeDay+1).padStart(2,"0")}　${date}</h3><p>${escapeHTML(day.summary||"この日の予定")}</p></div><span class="day-tag">${day.events.length} 件の予定</span></div>${renderFoodRecommendations(day)}<div id="schedule-alerts" class="schedule-alerts" role="status" hidden></div><div class="event-list" id="event-list">${day.events.map((e,i)=>`${i?`<div class="travel-gap" data-route-index="${i-1}">移動時間の目安を計算中…</div>`:""}<article class="event" draggable="true" data-id="${escapeHTML(e.id)}"><time class="event-time">${escapeHTML(TabiSchedule.clockLabel((TabiSchedule.clockMinutes(e.time)||0)+Number(e.dayOffset||0)*1440))}</time><span class="event-rail"></span><div class="event-card"><span class="event-emoji">${escapeHTML(e.emoji||"✦")}</span><div class="event-info"><strong>${escapeHTML(e.name)}</strong><small>${escapeHTML(e.kind)}</small>${e.place?`<small class="event-place">⌖ ${escapeHTML(e.place)}</small>`:""}${e.timeLocked?'<span class="time-lock-badge">時刻固定</span>':""}<small class="event-end">終了 ${escapeHTML(TabiSchedule.clockLabel((TabiSchedule.clockMinutes(e.time)||0)+Number(e.dayOffset||0)*1440+eventDurationMinutes(e.duration)))}</small></div><span class="event-duration">◷ ${escapeHTML(e.duration)}</span></div><span class="event-grip" aria-label="ドラッグして並べ替え">⠿</span></article>`).join("")}</div>`;
 enableDrag();drawRouteInfo(day);
}
function routeDurationLabel(seconds){const minutes=Math.max(1,Math.ceil(seconds/60)),days=Math.floor(minutes/1440),hours=Math.floor(minutes%1440/60),rest=minutes%60;return `約${days?`${days}日`:""}${hours?`${hours}時間`:""}${rest?`${rest}分`:days||hours?"":"1分"}`}
function parseClockMinutes(value){const match=/^(\d{1,2}):(\d{2})$/.exec(String(value||""));return match?Number(match[1])*60+Number(match[2]):null}
function formatClockMinutes(value){return `${String(Math.floor(value/60)).padStart(2,"0")}:${String(value%60).padStart(2,"0")}`}
function eventDurationMinutes(value){return TabiSchedule.durationMinutes(value)}
function durationLabel(minutes){return minutes<60?`約${minutes}分`:`約${Math.floor(minutes/60)}時間${minutes%60?`${minutes%60}分`:""}`}
function applyTravelAwareSchedule(day,segments,mode){return TabiSchedule.scheduleDay(day,segments,mode)}
function routeEvents(day){return day.events.map(event=>({name:event.name,kind:event.kind||"",duration:event.durationBase||event.duration||"",durationMode:event.durationMode||trip.initialTravelMode||"TRANSIT",place:event.place||"",origin:event.origin||""}))}
function routeKey(day){return JSON.stringify([trip.destination,routeEvents(day)])}
function drawRouteInfo(day){
 const status=$("#route-status"),data=day.routeData,result=data?.result;
 if(routesUpdatingAll&&routesUpdatingTrip===trip)status.textContent=trip.routeProgress||"全日程の移動時間を更新中…";
 else if(trip.routeModePending)status.textContent="未更新の日があります。「全日程を再計算」を押してください。";
 else if(data?.error)status.textContent=data.error;
 else status.textContent=day.scheduleIssues?.some(issue=>issue.type!=="unknown")?"固定時刻や終了時刻を確認してください。":result?.segments.some(item=>item.source==="area")?"場所未確定の区間は時間の幅で表示し、余裕を含めて調整しています。":"移動時間は概算です。時刻表・交通状況は含みません。";
 $("#route-retry").hidden=!trip.routeModePending&&!data?.error;
 for(const gap of document.querySelectorAll("#event-list .travel-gap")){const segment=result?.segments.find(item=>item.index===Number(gap.dataset.routeIndex));gap.textContent=data?.error?"移動時間を確認できません":segment?TabiSchedule.travelLabel(segment,travelMode):"移動時間の目安を計算中…"}
 const box=$("#schedule-alerts");if(!box)return;box.replaceChildren();box.hidden=!day.scheduleIssues?.length;
 for(const issue of day.scheduleIssues||[]){const note=document.createElement("p");note.textContent=issue.message;box.append(note)}
 for(const row of document.querySelectorAll("#event-list .event"))row.classList.toggle("has-conflict",Boolean(day.scheduleIssues?.some(issue=>issue.id===row.dataset.id&&issue.type!=="unknown")));
}
function updateRouteEstimates(all=false){
 if(!trip)return Promise.resolve();
 if(routesUpdatingAll&&routesUpdatingTrip===trip&&routesUpdatingMode===travelMode){drawRouteInfo(trip.days[activeDay]);return routeUpdatePromise}
 const sourceTrip=trip,mode=travelMode,requestId=++routeRequestId,days=all?[...trip.days]:[trip.days[activeDay]];
 routesUpdatingAll=all;routesUpdatingTrip=sourceTrip;routesUpdatingMode=mode;
 if(all){trip.routeModePending=true;trip.routeProgress=`全日程を更新中… 0/${days.length}日`;renderDay(false)}
 $("#share-button").disabled=true;
 const isCurrent=()=>trip===sourceTrip&&travelMode===mode&&requestId===routeRequestId;
 const work=(async()=>{
   const result=await TabiSchedule.recalculateDays(days,{mode,isCurrent,loadRoutes:async day=>{
     const key=routeKey(day);if(day.routeData?.key===key&&day.routeData.result)return day.routeData.result;
     const response=await fetch("/api/routes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({destination:sourceTrip.destination,travelMode:mode,events:routeEvents(day)})});
     const data=await response.json();if(!response.ok)throw new Error(data.error||"移動時間を更新できませんでした");if(!isCurrent()||routeKey(day)!==key)throw new Error("予定が更新されました。再計算してください。");day.routeData={key,result:data};return data;
   },onProgress:(done,total,day)=>{sourceTrip.routeProgress=`全日程を更新中… ${done}/${total}日`;if(sourceTrip.days[activeDay]===day)renderDay(false);else drawRouteInfo(sourceTrip.days[activeDay])}});
   if(!isCurrent()||result.cancelled)return;
   routesUpdatingAll=false;delete sourceTrip.routeProgress;if(all)sourceTrip.routeModePending=result.failures.length>0;
   renderDay(false);updateSaved();$("#share-button").disabled=Boolean(sourceTrip.routeModePending);persistDraft();
 })().catch(error=>{if(!isCurrent())return;routesUpdatingAll=false;if(all)sourceTrip.routeModePending=true;toast(error.message);drawRouteInfo(sourceTrip.days[activeDay]);updateSaved()});
 routeUpdatePromise=work;return work;
}
function enableDrag(){const list=$("#event-list");let dragged=null;list.querySelectorAll(".event").forEach(el=>{el.addEventListener("dragstart",e=>{dragged=el;el.classList.add("dragging");e.dataTransfer.effectAllowed="move"});el.addEventListener("dragend",()=>{el.classList.remove("dragging");list.querySelectorAll(".drop-target").forEach(x=>x.classList.remove("drop-target"))});el.addEventListener("dragover",e=>{e.preventDefault();if(dragged&&dragged!==el)el.classList.add("drop-target")});el.addEventListener("dragleave",()=>el.classList.remove("drop-target"));el.addEventListener("drop",e=>{e.preventDefault();el.classList.remove("drop-target");if(!dragged||dragged===el)return;const events=trip.days[activeDay].events;const from=events.findIndex(x=>x.id===dragged.dataset.id),to=events.findIndex(x=>x.id===el.dataset.id);const [moved]=events.splice(from,1);events.splice(to,0,moved);renderDay()})})}
function escapeHTML(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function safeOfficialURL(value){
  if(typeof value!=="string"||value.length>2048)return "";
  try{const url=new URL(value),host=url.hostname.toLowerCase();if(!["http:","https:"].includes(url.protocol)||url.username||url.password||!host.includes(".")||host.endsWith(".local")||host.endsWith(".localhost")||/^[\d.]+$/.test(host)||host.includes(":")||url.port&&!["80","443"].includes(url.port))return "";return url.href}catch{return ""}
}
function officialSiteKey(destination,event){return JSON.stringify([destination,event.name,event.place||"",event.origin||""])}
function currentOfficialSite(destination,event){
  const site=event.officialWebsite,ttl=site?.status==="found"?7*86400000:site?.status==="error"?5*60000:12*3600000;
  return site?.key===officialSiteKey(destination,event)&&site.checkedAt+ttl>Date.now()?site:null;
}
function renderOfficialSite(row,event,destination){
  const info=row.querySelector(".event-info");if(!info||event.editing)return;
  let holder=info.querySelector(".event-links");if(!holder){holder=document.createElement("div");holder.className="event-links";info.append(holder)}holder.replaceChildren();
  if(event.origin||/移動|戻る|向かう|帰路|往路/.test(event.name))return;
  const site=currentOfficialSite(destination,event),url=site?.status==="found"?safeOfficialURL(site.url):"";
  if(url){const link=document.createElement("a");link.href=url;link.target="_blank";link.rel="noopener noreferrer";link.textContent="公式サイト ↗";link.title=site.title||event.place||event.name;holder.append(link);return}
  if(!site){holder.textContent="公式サイトを検索中…";return}
  if(site.status==="skipped")return;
  const note=document.createElement("span");note.textContent=site.status==="error"?"公式サイトを検索できませんでした":"公式サイトを確認できませんでした";if(site.error)note.title=site.error;
  const retry=document.createElement("button");retry.type="button";retry.textContent="再検索";retry.addEventListener("click",()=>updateOfficialSites(true));holder.append(note,retry);
}
async function updateOfficialSites(refresh=false){
  if(!trip)return;const sourceTrip=trip,day=trip.days[activeDay];if(day.events.some(event=>event.editing))return;
  const renderLinks=()=>{if(trip!==sourceTrip||trip.days[activeDay]!==day)return;for(const row of document.querySelectorAll("#event-list .event")){const event=day.events.find(item=>item.id===row.dataset.id);if(event)renderOfficialSite(row,event,sourceTrip.destination)}};
  renderLinks();
  const needsSearch=day.events.some(event=>!event.origin&&!/移動|戻る|向かう|帰路|往路/.test(event.name)&&(!currentOfficialSite(sourceTrip.destination,event)||refresh&&currentOfficialSite(sourceTrip.destination,event)?.status!=="found"));
  if(!needsSearch)return;
  const snapshots=day.events.map(event=>({id:event.id,key:officialSiteKey(sourceTrip.destination,event),name:event.name,place:event.place||"",origin:event.origin||"",kind:event.kind||""}));
  const key=JSON.stringify([sourceTrip.destination,snapshots.map(({id,...event})=>event)]);
  let request=officialSiteRequests.get(key);
  if(!request){request=(async()=>{const response=await fetch("/api/official-sites",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({destination:sourceTrip.destination,refresh,events:snapshots.map(({name,place,origin,kind})=>({name,place,origin,kind}))})});const result=await response.json();if(!response.ok)throw new Error(result.error||"公式サイトを検索できませんでした");return result})();officialSiteRequests.set(key,request)}
  try{const result=await request;for(const site of result.sites||[]){const snapshot=snapshots[site.index],event=day.events.find(item=>item.id===snapshot?.id);if(!event||officialSiteKey(sourceTrip.destination,event)!==snapshot.key)continue;event.officialWebsite={...site,key:snapshot.key,checkedAt:Date.now()}}}
  catch(error){for(const snapshot of snapshots){const event=day.events.find(item=>item.id===snapshot.id);if(!event||officialSiteKey(sourceTrip.destination,event)!==snapshot.key||currentOfficialSite(sourceTrip.destination,event)?.status==="found")continue;event.officialWebsite={key:snapshot.key,url:"",status:"error",error:error.message,checkedAt:Date.now()}}}
  finally{if(officialSiteRequests.get(key)===request)officialSiteRequests.delete(key)}
  if(trip===sourceTrip){renderLinks();persistDraft()}
}
function renderDay(refreshRoutes=true){
  renderDayBase();const tabs=$("#day-tabs");
  if(!$("#add-day-button")){const add=document.createElement("button");add.type="button";add.className="day-tab add-day-tab";add.id="add-day-button";add.textContent="＋ 日程を追加";tabs.append(add);add.addEventListener("click",addDay)}
  const title=$("#day-content .day-title-row"),tools=document.createElement("div");tools.className="day-tools";tools.innerHTML='<button type="button" class="add-event-button">＋ 予定を追加</button><button type="button" class="remove-day-button">日程を削除</button>';
  if(activeDay>0)tools.insertAdjacentHTML("afterbegin",'<button type="button" class="copy-previous-day">前日をコピー</button>');title.append(tools);tools.querySelector(".copy-previous-day")?.addEventListener("click",copyPreviousDay);tools.querySelector(".add-event-button").addEventListener("click",addEvent);tools.querySelector(".remove-day-button").addEventListener("click",removeDay);
  const day=trip.days[activeDay],list=$("#event-list");if(day.summary)$("#day-content .day-title-row p").textContent=day.summary;if(!day.events.length)list.innerHTML='<p class="empty-day">予定はまだありません。「＋ 予定を追加」から自由に追加できます。</p>';
  list.querySelectorAll(".event").forEach(row=>{
    const event=day.events.find(x=>x.id===row.dataset.id),info=row.querySelector(".event-info");if(!event||!info)return;
    const controls=document.createElement("div");controls.className="event-actions";
    if(event.editing){
      row.draggable=false;row.classList.add("is-editing");
      const time=document.createElement("input");time.type="time";time.className="event-time-edit";time.value=event.time;time.setAttribute("aria-label","開始時刻");row.querySelector(".event-time").replaceWith(time);
      row.querySelector(".event-grip")?.remove();
      const fields=[["予定名","event-name-edit",event.name],["場所・メモ","event-kind-edit",event.kind],["お店・宿・施設名（到着地）","event-place-edit",event.place||""],["移動の出発地（任意）","event-origin-edit",event.origin||""],["所要時間（分）","event-duration-edit",eventDurationMinutes(event.duration)||60]];
      info.replaceChildren();for(const [caption,className,value] of fields){const label=document.createElement("label"),text=document.createElement("span"),input=document.createElement("input");label.className="edit-text-field";text.textContent=caption;input.className=className;input.value=value;if(className==="event-place-edit"){input.placeholder="例：お店やホテルの正式名称";input.maxLength=100}if(className==="event-duration-edit"){input.type="number";input.min="5";input.max="1440";input.step="5"}label.append(text,input);info.append(label)}
      const locked=document.createElement("label"),lockInput=document.createElement("input"),lockText=document.createElement("span");locked.className="edit-lock-field";lockInput.type="checkbox";lockInput.className="event-lock-edit";lockInput.checked=Boolean(event.timeLocked);lockText.textContent="予約などの開始時刻を固定";locked.append(lockInput,lockText);info.append(locked);
      row.querySelector(".event-duration")?.remove();controls.innerHTML='<button type="button" class="event-save">保存</button><button type="button" class="event-cancel">取消</button>';
      const timeLabel=document.createElement("label"),caption=document.createElement("span");timeLabel.className="edit-time-field";caption.textContent="開始時刻";timeLabel.append(caption,time);row.insertBefore(timeLabel,row.querySelector(".event-rail"));
    }else{controls.innerHTML='<button type="button" class="event-edit">編集</button><button type="button" class="event-delete">削除</button>';const grip=row.querySelector(".event-grip");if(grip)controls.append(grip)}
    row.append(controls);controls.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>handleEventAction(event.id,button.classList.contains("event-edit")?"edit":button.classList.contains("event-save")?"save":button.classList.contains("event-cancel")?"cancel":"delete")))
  });$("#add-day-button").disabled=routesUpdatingAll&&routesUpdatingTrip===trip;if(routesUpdatingAll&&routesUpdatingTrip===trip){tools.querySelectorAll("button").forEach(button=>button.disabled=true);list.querySelectorAll(".event-actions button").forEach(button=>button.disabled=true);list.querySelectorAll(".event").forEach(row=>row.draggable=false)}if(!day.events.some(event=>event.editing)){updateOfficialSites();if(refreshRoutes)updateRouteEstimates(Boolean(trip.routeModePending))}drawRouteInfo(day);persistDraft()
}
function foodUndoKey(day){return JSON.stringify(day.events.map(event=>[event.id,event.name,event.kind,event.place,event.origin,event.timeLocked,event.scheduleBaseTime||event.time,event.durationManual]))}
function applyFoodPick(index){
 const sourceTrip=trip,day=trip?.days[activeDay],pick=day?.foodRecommendations?.[index];if(!pick)return;
 if(routesUpdatingAll&&routesUpdatingTrip===trip)return toast("移動時間の更新が終わってからお店を選んでください。");
 const before=structuredClone({events:day.events,routeData:day.routeData,scheduleIssues:day.scheduleIssues});
 const result=TabiSchedule.applyFoodRecommendation(day,pick,{targetId:foodTarget(day)?.id||"",time:day.foodNewTime||"12:00",id:TabiSchedule.createId(),mode:travelMode});
 if(result.error)return toast(result.error);
 const appliedKey=foodUndoKey(day);renderDay();toast(`${pick.name}を${result.replaced?"食事予定に入れました":"追加しました"}`,{label:"元に戻す",run:()=>{
  if(trip!==sourceTrip||!trip.days.includes(day))return toast("元の旅程を開いてからやり直してください。");
  if(foodUndoKey(day)!==appliedKey)return toast("その後に予定が変更されています。編集から調整してください。");
  Object.assign(day,before);if(trip.days[activeDay]===day)renderDay();else persistDraft();toast("グルメの変更を元に戻しました");
 }});
}
function handleEventAction(id,action){const events=trip.days[activeDay].events,index=events.findIndex(event=>event.id===id);if(index<0)return;const event=events[index],row=[...$("#event-list").querySelectorAll(".event")].find(el=>el.dataset.id===id);
  if(action==="edit"){event.original={time:event.time,scheduleBaseTime:event.scheduleBaseTime,dayOffset:event.dayOffset,name:event.name,kind:event.kind,place:event.place,origin:event.origin,duration:event.duration,durationBase:event.durationBase,durationManual:event.durationManual,timeLocked:event.timeLocked};event.editing=true;renderDay();[...$("#event-list").querySelectorAll(".event")].find(el=>el.dataset.id===id)?.querySelector(".event-name-edit")?.focus();return}
  if(action==="cancel"){if(event.isNew)events.splice(index,1);else{Object.assign(event,event.original||{});delete event.original;delete event.editing}renderDay();return}
  if(action==="save"){const name=row.querySelector(".event-name-edit").value.trim(),minutes=Number(row.querySelector(".event-duration-edit").value);if(!name){toast("予定の名前を入力してください");return}if(!Number.isInteger(minutes)||minutes<5||minutes>1440){toast("所要時間は5〜1440分で入力してください");return}const changedDuration=minutes!==eventDurationMinutes(event.original?.duration);event.time=row.querySelector(".event-time-edit").value||"12:00";event.scheduleBaseTime=event.time;event.dayOffset=0;event.timeLocked=row.querySelector(".event-lock-edit").checked;event.name=name;event.kind=row.querySelector(".event-kind-edit").value.trim()||"自由時間";event.place=row.querySelector(".event-place-edit").value.trim();event.origin=row.querySelector(".event-origin-edit").value.trim();event.duration=durationLabel(minutes);event.durationBase=changedDuration?event.duration:event.original?.durationBase;event.durationManual=changedDuration||Boolean(event.original?.durationManual);delete event.original;delete event.editing;delete event.isNew;renderDay();return}events.splice(index,1);renderDay()
}
$("#day-content").addEventListener("click",event=>{const button=event.target.closest(".food-pick-button");if(button&&!button.disabled)applyFoodPick(Number(button.dataset.foodPick))});
$("#day-content").addEventListener("change",event=>{const day=trip?.days[activeDay];if(!day)return;if(event.target.id==="food-target"){day.foodTargetId=event.target.value;renderDay(false)}if(event.target.id==="food-new-time"){day.foodNewTime=event.target.value;renderDay(false)}});
function addEvent(){const events=trip.days[activeDay].events;events.push({id:`custom-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,name:"新しい予定",kind:"場所やメモを追加",emoji:"✦",duration:"約1時間",place:"",time:"12:00",scheduleBaseTime:"12:00",editing:true,isNew:true});renderDay();$("#event-list .event:last-of-type .event-name-edit")?.focus()}
function copyPreviousDay(){if(activeDay<1)return;const source=trip.days[activeDay-1],target=trip.days[activeDay];if(target.events.length&&!window.confirm("この日の予定を前日の予定で置き換えますか？"))return;const journeys=target.events.filter(event=>TabiSchedule.journeyRole(event,trip)!=="local");target.events=source.events.filter(event=>TabiSchedule.journeyRole(event,trip)==="local").map(event=>{const copy={...event,id:TabiSchedule.createId()};delete copy.editing;delete copy.original;delete copy.isNew;return copy});target.events.unshift(...journeys.filter(event=>TabiSchedule.journeyRole(event,trip)==="outbound"));target.events.push(...journeys.filter(event=>TabiSchedule.journeyRole(event,trip)==="return"));delete target.routeData;renderDay();toast("前日の予定をコピーしました。往路と帰路は保持しています。")}
async function addDay(){if(trip.days.length>=21){toast("旅程は最大21日までです");return}const button=$("#add-day-button"),next=new Date(trip.days[trip.days.length-1].date);button.disabled=true;next.setDate(next.getDate()+1);const date=localISO(next);try{const response=await fetch("/api/itinerary",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...trip,startDate:date,endDate:date,extension:true})});const result=await response.json();if(!response.ok)throw new Error(result.error||"予定を作成できませんでした。");const day=result.days?.[0];if(!day)throw new Error("APIから予定を受け取れませんでした。");const events=day.events.map((event,index)=>({...event,durationMode:travelMode,id:`ai-${Date.now()}-extra-${index}`}));if(trip.departurePoint)trip.days[trip.days.length-1].events=trip.days[trip.days.length-1].events.filter(event=>TabiSchedule.journeyRole(event,trip)!=="return");trip.days.push({date:parseLocal(date),summary:day.summary||"追加した日のおすすめプラン",foodRecommendations:day.foodRecommendations||[],events});trip.endDate=date;$("#end-date").value=date;activeDay=trip.days.length-1;trip.category=result.category||trip.category;render();$("#results").scrollIntoView({behavior:"smooth",block:"start"})}catch(error){toast(error.message||"予定を作成できませんでした。")}finally{if($("#add-day-button"))$("#add-day-button").disabled=false}}
function removeDay(){if(trip.days.length<=1){toast("日程は1日以上必要です");return}TabiSchedule.removeDay(trip,activeDay);$("#end-date").value=trip.endDate;activeDay=Math.min(activeDay,trip.days.length-1);trip.routeModePending=true;render();toast("日程を削除し、往路と帰路を残った日程へ移しました。")}
function readForm(){return {departurePoint:$("#departure-point").value.trim(),destination:$("#destination").value,startDate:$("#start-date").value,endDate:$("#end-date").value,pace:$("#pace").value,interests:[...document.querySelectorAll("#interest-chips input:checked")].map(x=>x.value)}}
async function generate(scroll=false){const data={...readForm(),travelMode};if(!data.destination.trim())return toast("行き先を入力してください");if(!data.startDate||!data.endDate)return toast("出発日と帰着日を設定してください");const count=dayCount(data.startDate,data.endDate);if(count<1||count>21)return toast("旅行日数は1〜21日の範囲で設定してください。");if(data.startDate>data.endDate)return toast("帰着日は出発日以降に設定してください");const button=$("#planner-form .primary-button"),original=button.innerHTML,repeat=$("#regenerate-button");button.disabled=true;repeat.disabled=true;button.innerHTML="<span>◌</span> AIが旅程を作成中…";try{const response=await fetch("/api/itinerary",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.error||"旅程を生成できませんでした。");if(!Array.isArray(result.days)||result.days.length!==count)throw new Error("APIから日数の合わない旅程が返りました。もう一度お試しください。");trip={...data,initialTravelMode:travelMode,id:TabiSchedule.createId(),category:result.category||"AIが提案する旅",days:result.days.map((day,index)=>{const date=parseLocal(data.startDate);date.setDate(date.getDate()+index);return {date,summary:day.summary||"この日のおすすめプラン",foodRecommendations:day.foodRecommendations||[],events:day.events.map((event,eventIndex)=>({...event,durationMode:travelMode,id:`ai-${Date.now()}-${index}-${eventIndex}`}))}})};activeDay=0;render();if(scroll)$("#results").scrollIntoView({behavior:"smooth",block:"start"})}catch(error){toast(error.message||"旅程を生成できませんでした。時間をおいて再度お試しください。")}finally{button.disabled=false;button.innerHTML=original;repeat.disabled=!trip}}
function openSavedDialog(){savedView="active";renderSavedTrips();$("#saved-dialog").showModal()}
function updateStorageLists(data){savedTrips=data.saved||[];deletedTrips=data.deleted||[];updateSaved();if($("#saved-dialog").open)renderSavedTrips()}
function renderSavedTrips(){
 const list=$("#saved-trip-list"),empty=$("#saved-dialog-empty"),items=savedView==="deleted"?deletedTrips:savedTrips;list.replaceChildren();empty.hidden=items.length>0;empty.textContent=savedView==="deleted"?"削除した旅程はありません。":"保存した旅程はまだありません。";
 $("#saved-view-active").setAttribute("aria-pressed",String(savedView==="active"));$("#saved-view-deleted").setAttribute("aria-pressed",String(savedView==="deleted"));
 for(const item of items){const row=document.createElement("article"),open=document.createElement(savedView==="active"?"button":"div"),copy=document.createElement("span"),title=document.createElement("strong"),summary=document.createElement("span"),action=document.createElement("button");row.className="saved-trip-row";open.className="saved-trip-open";title.className="saved-trip-title";title.textContent=item.departurePoint?`${item.departurePoint} → ${item.destination}`:item.destination;copy.className="saved-trip-summary";summary.textContent=`${dateRange(item.startDate,item.endDate)} ・ ${item.days.length}日間`;copy.append(title,summary);open.append(copy);action.type="button";action.className=savedView==="deleted"?"saved-trip-restore":"saved-trip-delete";action.textContent=savedView==="deleted"?"復元":"削除";action.setAttribute("aria-label",`${item.destination}の旅程を${action.textContent}`);
 if(savedView==="active"){open.type="button";open.addEventListener("click",()=>{restoreDraft({...item,activeDay:0});$("#saved-dialog").close();$("#results").scrollIntoView({behavior:"smooth"})});action.addEventListener("click",()=>deleteSavedTrip(item))}else action.addEventListener("click",()=>restoreSavedTrip(item));row.append(open,action);list.append(row)}
}
async function deleteSavedTrip(item){deletingTripIds.add(item.id);try{if(trip?.id===item.id){clearTimeout(draftTimer);await draftQueue}const response=await fetch(`/api/storage/saved?${new URLSearchParams({id:item.id})}`,{method:"DELETE"});if(!response.ok)throw new Error("旅程を削除できませんでした");updateStorageLists(await response.json());toast("旅程を削除しました",{label:"元に戻す",run:()=>restoreSavedTrip(item)})}catch(error){toast(error.message)}finally{deletingTripIds.delete(item.id)}}
async function restoreSavedTrip(item){try{const response=await fetch("/api/storage/saved/restore",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id})});if(!response.ok)throw new Error("旅程を復元できませんでした");updateStorageLists(await response.json());toast("旅程を復元しました")}catch(error){toast(error.message)}}
function updateSaved(){$("#saved-count").textContent=savedTrips.length;$("#mobile-saved-count").textContent=savedTrips.length;const button=$("#save-button");if(!trip)return;const exists=savedTrips.some(x=>x.id===trip.id);button.disabled=exists||routesUpdatingAll;button.classList.toggle("is-saved",exists);button.innerHTML=exists?"<span>✓</span> 保存済み":"<span>♡</span> 保存する"}
async function saveTrip(){if(!trip||savedTrips.some(item=>item.id===trip.id)||routesUpdatingAll)return;const button=$("#save-button"),sourceTrip=trip;button.disabled=true;try{const response=await fetch("/api/storage/saved",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({trip:serializeTrip({...sourceTrip,activeDay})})});if(!response.ok)throw new Error("旅程を保存できませんでした");const data=await response.json();sourceTrip.id=data.trip.id;updateStorageLists(data);toast("旅程をデータベースに保存しました")}catch(error){toast(error.message)}finally{updateSaved()}}
function toast(message,action){const el=$("#toast"),text=document.createElement("span");text.textContent=message;el.replaceChildren(text);if(action){const button=document.createElement("button");button.type="button";button.textContent=action.label;button.addEventListener("click",action.run);el.append(button)}el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),action?20000:3200)}
async function copyTrip(){
 if(!trip)return;if(trip.days.some(day=>day.events.some(event=>event.editing))){toast("予定の編集を保存してからコピーしてください");return}
 const sourceTrip=trip,mode=travelMode;await updateRouteEstimates(true);if(trip!==sourceTrip||travelMode!==mode){toast("旅程が切り替わりました。もう一度コピーしてください");return}if(trip.routeModePending){toast("全日程の移動時間を更新してからコピーしてください");return}
 const text=`${trip.departurePoint?`${trip.departurePoint} → `:""}${trip.destination}の旅程\n${dateRange(trip.startDate,trip.endDate)}\n移動手段：${{TRANSIT:"電車・バス",WALK:"徒歩",DRIVE:"車"}[travelMode]}\n\n${trip.days.map((day,i)=>`DAY ${i+1} ${dateLabel(day.date,{month:"numeric",day:"numeric",weekday:"long"})}\n${day.events.map((e,index)=>`${index?`${TabiSchedule.travelLabel(day.routeData.result.segments.find(item=>item.index===index-1),travelMode)}\n`:""}${TabiSchedule.clockLabel((TabiSchedule.clockMinutes(e.time)||0)+Number(e.dayOffset||0)*1440)} ${e.name} (${e.duration})${e.timeLocked?"［時刻固定］":""}${safeOfficialURL(currentOfficialSite(trip.destination,e)?.url)?`\n  公式サイト：${safeOfficialURL(currentOfficialSite(trip.destination,e)?.url)}`:""}`).join("\n")}${day.scheduleIssues?.length?`\n注意：${day.scheduleIssues.map(issue=>issue.message).join(" / ")}`:""}`).join("\n\n")}\n\n※ 移動時間は概算です。天気・営業時間・交通機関を事前にご確認ください。`;
 try{await navigator.clipboard.writeText(text);toast("旅程をコピーしました")}catch{toast("この環境ではコピーできませんでした")}
}
document.querySelectorAll(".chip input").forEach(input=>input.addEventListener("change",()=>input.closest(".chip").classList.toggle("selected",input.checked)));$("#planner-form").addEventListener("submit",e=>{e.preventDefault();generate()});$("#regenerate-button").addEventListener("click",()=>generate());$("#save-button").addEventListener("click",saveTrip);$("#share-button").addEventListener("click",copyTrip);$("#saved-nav").addEventListener("click",openSavedDialog);$("#mobile-saved-nav").addEventListener("click",openSavedDialog);$("#saved-view-active").addEventListener("click",()=>{savedView="active";renderSavedTrips()});$("#saved-view-deleted").addEventListener("click",()=>{savedView="deleted";renderSavedTrips()});$("#route-retry").addEventListener("click",()=>updateRouteEstimates(true));$("#saved-dialog-close").addEventListener("click",()=>$("#saved-dialog").close());$("#saved-dialog").addEventListener("click",event=>{if(event.target===$("#saved-dialog"))$("#saved-dialog").close()});$("#route-mode").addEventListener("change",event=>{if(trip?.days.some(day=>day.events.some(item=>item.editing))){event.target.value=travelMode;toast("予定の編集を保存してから移動手段を変更してください");return}travelMode=event.target.value;if(trip){trip.travelMode=travelMode;persistDraft();updateRouteEstimates(true)}});initializeDates();renderEmpty();initializeStorage();checkApiStatus();
